name: full_run
CUDA_VISIBLE_DEVICES: "0,1,3,4"
batch_size: 128
epochs: 15
num_workers: 4
img_height: 32
img_width: 128
train_json: dataset/TextOCR/TextOCR_0.1_train.json
val_json: dataset/TextOCR/TextOCR_0.1_val.json
image_root: dataset/TextOCR/train_val_images/train_images
