json_train: "json/TextOCR_train_10.json"
json_val: "json/TextOCR_val_5.json"
image_root: "dataset/TextOCR/train_val_images/train_images"
epochs: 5
batch_size: 8
num_workers: 4
learning_rate: 0.0001
model: "transformer"
checkpoint: "checkpoints/transformer_word_test10.pth"
img_width: 128
img_height: 32
max_train_images: null
max_val_images: null
chars: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
vis_path: "vis/transformer_word"
print_results: True