json_train: "json/FUNSD/funsd_train_textocr_style_filtered.json"
json_val: "json/FUNSD/funsd_val_textocr_style_filtered.json"
image_root: "dataset/FUNSD"
epochs: 150
batch_size: 32
num_workers: 4
learning_rate: 0.00001
model: "transformer_line"
dataset: "FUNSD"
checkpoint: "checkpoints/transformer_funsd.pth"
img_height: 32
img_width: 1280
max_train_images: None
max_val_images: None
chars: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+[]{}|;:'\\\",.<>?/`~\\ "
vis_path: "vis/funsd_transformer_line"
print_results: True
