json_train: "json/FUNSD/funsd_train_textocr_style_filtered_10.json"
json_val: "json/FUNSD/funsd_val_textocr_style_filtered_5.json"
image_root: "dataset/FUNSD"

epochs: 60
batch_size: 4
num_workers: 4
learning_rate: 0.0005
model: "transformer_attention"
dataset: "FUNSD"
checkpoint: "checkpoints/attention_FUNSD.pth"

img_height: 32
img_width: 512
max_train_images: None
max_val_images: None

chars: "<pad><sos><eos>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+[]{}|;:'\\\",.<>?/`~ "

vis_path: "vis/overfit_attention"
print_results: True

gpus: 2